# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

GOLDEN_RATIO = (1 + 5 ** 0.5) / 2

def n_fib(f)
  log_value = Math.log(f * Math.sqrt(5), GOLDEN_RATIO) + 0.5
  log_value.floor
end

def even_sum(f)
  k = n_fib(f) / 3
  phi = GOLDEN_RATIO ** 3
  psi = (-GOLDEN_RATIO) ** (-3)
  (1 / Math.sqrt(5)) * (phi * (1 - phi ** k) / (1 - phi) - psi * (1 - psi ** k) / (1 - psi))
end

puts even_sum(4000000)
